- frontend/src/pages/Home.tsx
> frontend dic_src init

- docker-compose.yml
- frontend/package-lock.json
- frontend/package.json
- frontend/yarn.lock
> to use Native Base

- frontend/package-lock.json
- frontend/package.json
- frontend/yarn.lock
close #8 
react-native-calendarsのインストール
> react-native-calendarsをインストールした

- frontend/src/pages/signed/Calendar.jsx
> Calendarの関数名を変更

- frontend/src/components/Sign_Login.jsx
- frontend/src/pages/Signup.jsx
- frontend/src/pages/login.jsx
#19 
とりあえず形だけコンポーネント追加
引き続き作ります
> create signUp_Login component

- frontend/package-lock.json
- frontend/package.json
- frontend/yarn.lock
close #12
react-native-swiperをインストールした
> react-native-swiperをインストール

- src/components/MusicInfo.jsx
- src/pages/signed/MyPage.jsx
Close #33
MyPageやMyCalendarに使う楽曲情報表示UIの概形のコンポーネントを作成した
作成したコンポーネントをMyPageで使った
動きますが機能として不完全なので適宜issueを立てて修正してください
> 楽曲情報表示のコンポーネントを追加・MyPageに使用

- src/components/MusicInfo.jsx
#36 
スタイルシートが反映されるように、以下のように修正
<hoge>
　<Center/>
　<Text/>
</hoge>
<hoge>
　<Center>
　　<Text/>
　</Center>
</hoge>
> スタイルシートが反映されるように修正

- src/components/MusicInfo.jsx
- src/components/MusicInfoItem.jsx
- src/pages/signed/MyPage.jsx
close #36 
MusicInfoをコンポーネントに分割した
MusicInfoに画像を挿入できるようにした
> issue#36を解決

- package-lock.json
- package.json
Close #41
react-native-vector-iconsをインストールした
> react-native-vector-iconsをインストール

- src/components/MusicInfo.jsx
- src/components/MusicInfoList.jsx
- src/pages/signed/MyCalendar.jsx
- src/pages/signed/MyPage.jsx
#34
MusicInfoListの作成
カレンダーページのカレンダー下部にMusicInfoを表示
> カレンダー下にMusicInfoが表示されるようにした

- src/pages/Home.jsx
> ボタンとフッターを追加

- src/pages/signed/MyCalendar.jsx
> 選択した日付をマークできるようにした

- src/pages/Signup.jsx
- src/pages/login.jsx
> login and SignUp

- src/pages/Home.jsx
> ボタンの間隔をつくった

- src/components/MusicInfoList.jsx
- src/pages/signed/MyCalendar.jsx
#34 
#11 
カレンダーで選択した日付にリリース予定のMusicInfoのみをカレンダー下に表示する処理を追加
> 選択した日付のMusicInfoを表示

- src/components/SignedFooter.jsx
- src/pages/signed/MyCalendar.jsx
- src/pages/signed/MyPage.jsx
> フッターでの画面遷移を実装した

- App.js
- package.json
- src/components/ItemSearch.jsx
- src/components/MusicInfo.jsx
- src/components/Result.jsx
- src/pages/Home.jsx
- src/pages/signed/Insert.jsx
- src/utils/API.js
> add func api

- package-lock.json
- src/components/AddMusic.jsx
- src/components/SignedFooter.jsx
- src/pages/signed/MyPage.jsx
Close #59
楽曲追加ボタンとフッターを同時に使用できるようにした
背景が1色になるバグを修正した
画面遷移が未実装
MyPageのUIが崩れる恐れあり
> 楽曲追加ボタンとフッター間のバグ修正と背景修正

- src/components/AddMusic.jsx
> プラスボタンに画面遷移を実装

- src/components/SignedFooter.jsx
- src/pages/signed/MyCalendar.jsx
- src/pages/signed/MyPage.jsx
> カレンダーとマイページのUIを修正

- src/components/MusicInfo.jsx
- src/components/MusicInfoItem.jsx
- src/components/MusicInfoList.jsx
- src/pages/signed/MyPage.jsx
close #67 
MusicInfoListをきれいにした
> MusicInfoListを修正

- src/components/AddMusic.jsx
- src/components/SignedFooter.jsx
- src/pages/signed/MyCalendar.jsx
- src/pages/signed/MyPage.jsx
close #75 
AddMusicの位置を調整
MyCalendarにAddMusicを追加
SignedFooterの調整
> AddMusicなどのUIを調整

- src/pages/signed/MyCalendar.jsx
- src/pages/signed/MyPage.jsx
close #70
MusicInfoListが2列で表示されるように修正した
> MusicInfoListを2列にした
